### ISSUE TITLE
Version comparison failed: '<' not supported between instances of 'str' and 'int' (hashtag82667)

### ISSUE THREAD

**Issue by vikramsubramanian** [Mayil-AI-Sandbox/ansible_jan19#30]
hashtaghashtaghashtag Summary

```yaml
- name: Test
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: "Test"
      when: '"1.6-6" is version ("1.6.3-3", ">=")'
```

The versions are clearly not int, they are both strings. But I get the error above.

For many other combinations, it work, but not for this.

The error happens under different ansibe versions like 7.7.0 or 2.7.7.

hashtaghashtaghashtag Issue Type

Bug Report

hashtaghashtaghashtag Component Name

version

hashtaghashtaghashtag Ansible Version

```console
$ ansible --version

> ansible --version                    
ERROR: Ansible requires the locale encoding to be UTF-8; Detected ISO8859-1.
```

```console
> LC_ALL=C ansible --version
ERROR: Ansible requires the locale encoding to be UTF-8; Detected None.
```

```console
> LC_ALL=C.utf8 ansible --version
ansible [core 2.14.11]
  config file = /home/klaus/.ansible.cfg
  configured module search path = ['/home/klaus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/klaus/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.7 (main, Dec  8 2023, 14:22:46) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

(It is strange that there is a utf8 for C as C is per definition plain ASCII!

hashtaghashtaghashtag Configuration

```console
hashtag if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
```

Doesn't apply, I have the error under many different configurations

hashtaghashtaghashtag OS / Environment

Devuan but doesn't matter

hashtaghashtaghashtag Steps to Reproduce

```yaml
- name: Test
  hosts: all
  gather_facts: false
  tasks:
    - debug:
        msg: "Test"
      when: '"1.6-6" is version ("1.6.3-3", ">=")'
```

The versions are clearly not int, they are both strings. But I get the error above.

For many other combinations, it work, but not for this.

The error happens under different ansibe versions like 7.7.0 or 2.7.7.

hashtaghashtaghashtag Expected Results

It works

hashtaghashtaghashtag Actual Results

It doesn't work

hashtaghashtaghashtag Code of Conduct

- [ ] I agree to follow the Ansible Code of Conduct
)
